name: frontend
description: "LogiQ App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  gap: ^3.0.1
  go_router: ^15.1.2
  http: ^1.4.0
  google_fonts: ^6.1.0
  fl_chart: ^1.0.0
  font_awesome_flutter: ^10.8.0
  percent_indicator: ^4.2.5
  pin_code_fields: ^8.0.1
  collection: ^1.18.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  image_picker: ^1.2.0
  video_player: ^2.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/guide/images/
    - assets/guide/videos/
    - assets/questions/
